using System.Security.Cryptography;
using System.Text;
using System.Text.Encodings.Web;
using System.Text.Json;
using AudioText.Core.Models;

namespace AudioText.Infrastructure.Services;

/// <summary>
/// 基于 JSON 文件的本地视频分析记忆数据库。
/// Local JSON-file video analysis memory database.
/// 最近修改时间：2026-06-25；修改人：GG。
/// </summary>
public sealed class VideoAnalysisMemoryStore
{
    private const int SchemaVersion = 1;
    private const string DatabaseFileName = "video-analysis-memory.json";

    private static readonly JsonSerializerOptions JsonOptions = new()
    {
        Encoder = JavaScriptEncoder.UnsafeRelaxedJsonEscaping,
        PropertyNameCaseInsensitive = true,
        WriteIndented = true
    };

    private readonly SemaphoreSlim _gate = new(1, 1);
    private readonly string _databasePath;

    /// <summary>
    /// 创建记忆数据库服务，并确保数据库目录存在。
    /// Create the memory database service and ensure the database directory exists.
    /// 最近修改时间：2026-06-25；修改人：GG。
    /// </summary>
    public VideoAnalysisMemoryStore(string databaseDirectory)
    {
        ArgumentException.ThrowIfNullOrWhiteSpace(databaseDirectory);

        Directory.CreateDirectory(databaseDirectory);
        _databasePath = Path.Combine(databaseDirectory, DatabaseFileName);
    }

    /// <summary>
    /// 记忆数据库文件路径，供界面日志和目录展示使用。
    /// Memory database file path used by UI logs and directory display.
    /// 最近修改时间：2026-06-25；修改人：GG。
    /// </summary>
    public string DatabasePath => _databasePath;

    /// <summary>
    /// 按来源链接查找已经转写过的视频；用于重复视频跳过下载和 whisper。
    /// Find a previously transcribed video by source URL so repeated videos can skip download and whisper.
    /// 最近修改时间：2026-06-25；修改人：GG。
    /// </summary>
    public async Task<VideoAnalysisMemoryEntry?> FindBySourceUrlAsync(
        string sourceUrl,
        CancellationToken cancellationToken)
    {
        ArgumentException.ThrowIfNullOrWhiteSpace(sourceUrl);

        var sourceKey = BuildSourceKey(sourceUrl);
        await _gate.WaitAsync(cancellationToken);
        try
        {
            var database = await ReadDatabaseUnsafeAsync(cancellationToken);
            return database.Entries.FirstOrDefault(entry =>
                entry.SourceKey.Equals(sourceKey, StringComparison.OrdinalIgnoreCase)
                && !string.IsNullOrWhiteSpace(entry.TranscriptText));
        }
        finally
        {
            _gate.Release();
        }
    }

    /// <summary>
    /// 查找同一发布人的往期视频摘要，供 AI 核查时作为背景参考。
    /// Find historical videos from the same publisher for AI verification background.
    /// 最近修改时间：2026-06-25；修改人：GG。
    /// </summary>
    public async Task<IReadOnlyList<VideoMemoryReference>> FindPublisherReferencesAsync(
        VideoSourceMetadata metadata,
        string? currentSourceUrl,
        int maxCount,
        CancellationToken cancellationToken)
    {
        ArgumentNullException.ThrowIfNull(metadata);

        var publisherName = NormalizeText(metadata.PublisherName);
        if (string.IsNullOrWhiteSpace(publisherName) || maxCount <= 0)
        {
            return Array.Empty<VideoMemoryReference>();
        }

        var website = NormalizeText(metadata.Website);
        var currentSourceKey = string.IsNullOrWhiteSpace(currentSourceUrl)
            ? null
            : BuildSourceKey(currentSourceUrl);

        await _gate.WaitAsync(cancellationToken);
        try
        {
            var database = await ReadDatabaseUnsafeAsync(cancellationToken);
            return database.Entries
                .Where(entry => !string.IsNullOrWhiteSpace(entry.PublisherName))
                .Where(entry => string.Equals(
                    NormalizeText(entry.PublisherName),
                    publisherName,
                    StringComparison.OrdinalIgnoreCase))
                .Where(entry => string.IsNullOrWhiteSpace(website)
                    || string.IsNullOrWhiteSpace(entry.Website)
                    || string.Equals(NormalizeText(entry.Website), website, StringComparison.OrdinalIgnoreCase))
                .Where(entry => currentSourceKey is null
                    || !entry.SourceKey.Equals(currentSourceKey, StringComparison.OrdinalIgnoreCase))
                .Where(entry => entry.LastEvaluatedAt.HasValue)
                .OrderByDescending(entry => entry.LastEvaluatedAt ?? entry.LastAccessedAt)
                .Take(maxCount)
                .Select(entry => entry.ToReference())
                .ToList();
        }
        finally
        {
            _gate.Release();
        }
    }

    /// <summary>
    /// 记录或更新本次任务生成的转写文本，并增加任务次数。
    /// Record or update the transcript generated by this task and increment the task count.
    /// 最近修改时间：2026-06-25；修改人：GG。
    /// </summary>
    public async Task<VideoAnalysisMemoryEntry> RecordTranscriptAsync(
        string sourceUrl,
        VideoSourceMetadata metadata,
        string title,
        string transcriptText,
        string? transcriptPath,
        CancellationToken cancellationToken)
    {
        ArgumentException.ThrowIfNullOrWhiteSpace(sourceUrl);
        ArgumentNullException.ThrowIfNull(metadata);
        ArgumentException.ThrowIfNullOrWhiteSpace(transcriptText);

        var now = DateTimeOffset.Now;
        var sourceKey = BuildSourceKey(sourceUrl);
        await _gate.WaitAsync(cancellationToken);
        try
        {
            var database = await ReadDatabaseUnsafeAsync(cancellationToken);
            var entries = database.Entries.ToList();
            var index = entries.FindIndex(entry => entry.SourceKey.Equals(sourceKey, StringComparison.OrdinalIgnoreCase));
            var existing = index >= 0 ? entries[index] : null;
            var entry = BuildTranscriptEntry(
                existing,
                sourceKey,
                sourceUrl,
                metadata,
                title,
                transcriptText,
                transcriptPath,
                now);

            if (index >= 0)
            {
                entries[index] = entry;
            }
            else
            {
                entries.Add(entry);
            }

            await WriteDatabaseUnsafeAsync(new VideoAnalysisMemoryDatabase(SchemaVersion, entries.ToArray()), cancellationToken);
            return entry;
        }
        finally
        {
            _gate.Release();
        }
    }

    /// <summary>
    /// 记录重复视频复用转写文本的任务访问，避免重新下载时仍能统计使用次数。
    /// Record a repeated-video reuse so task count still reflects user runs without downloading again.
    /// 最近修改时间：2026-06-25；修改人：GG。
    /// </summary>
    public async Task<VideoAnalysisMemoryEntry?> TouchReuseAsync(
        string sourceUrl,
        CancellationToken cancellationToken)
    {
        ArgumentException.ThrowIfNullOrWhiteSpace(sourceUrl);

        var sourceKey = BuildSourceKey(sourceUrl);
        await _gate.WaitAsync(cancellationToken);
        try
        {
            var database = await ReadDatabaseUnsafeAsync(cancellationToken);
            var entries = database.Entries.ToList();
            var index = entries.FindIndex(entry => entry.SourceKey.Equals(sourceKey, StringComparison.OrdinalIgnoreCase));
            if (index < 0)
            {
                return null;
            }

            var entry = entries[index] with
            {
                LastAccessedAt = DateTimeOffset.Now,
                TaskCount = Math.Max(0, entries[index].TaskCount) + 1
            };
            entries[index] = entry;
            await WriteDatabaseUnsafeAsync(new VideoAnalysisMemoryDatabase(SchemaVersion, entries.ToArray()), cancellationToken);
            return entry;
        }
        finally
        {
            _gate.Release();
        }
    }

    /// <summary>
    /// 记录或更新最近一次 AI 核查结果；该操作不增加任务次数，任务次数由转写或复用入口统计。
    /// Record or update the latest AI evaluation result; task count is tracked by transcript/reuse entry points.
    /// 最近修改时间：2026-06-25；修改人：GG。
    /// </summary>
    public async Task<VideoAnalysisMemoryEntry> RecordEvaluationAsync(
        string sourceUrl,
        VideoSourceMetadata metadata,
        string title,
        string transcriptText,
        string? transcriptPath,
        AiVideoEvaluationResult evaluationResult,
        string? reportPath,
        CancellationToken cancellationToken)
    {
        ArgumentException.ThrowIfNullOrWhiteSpace(sourceUrl);
        ArgumentNullException.ThrowIfNull(metadata);
        ArgumentException.ThrowIfNullOrWhiteSpace(transcriptText);
        ArgumentNullException.ThrowIfNull(evaluationResult);

        var now = DateTimeOffset.Now;
        var sourceKey = BuildSourceKey(sourceUrl);
        await _gate.WaitAsync(cancellationToken);
        try
        {
            var database = await ReadDatabaseUnsafeAsync(cancellationToken);
            var entries = database.Entries.ToList();
            var index = entries.FindIndex(entry => entry.SourceKey.Equals(sourceKey, StringComparison.OrdinalIgnoreCase));
            var existing = index >= 0 ? entries[index] : null;
            var transcriptEntry = BuildTranscriptEntry(
                existing,
                sourceKey,
                sourceUrl,
                metadata,
                title,
                transcriptText,
                transcriptPath,
                now,
                incrementTaskCount: existing is null);
            var entry = transcriptEntry with
            {
                LastAccessedAt = now,
                LastEvaluatedAt = now,
                LastReportPath = reportPath,
                Category = evaluationResult.Category,
                OverallScore = evaluationResult.OverallScore,
                TruthfulnessScore = evaluationResult.TruthfulnessScore,
                TimelinessScore = evaluationResult.TimelinessScore,
                InformationProfessionalismScore = evaluationResult.InformationProfessionalismScore,
                EntertainmentScore = evaluationResult.EntertainmentScore,
                EmotionalGuidanceSuspicionScore = evaluationResult.EmotionalGuidanceSuspicionScore,
                Verdict = evaluationResult.Verdict,
                KeyClaims = evaluationResult.KeyClaims.ToArray(),
                ClaimEvaluations = evaluationResult.ClaimEvaluations.ToArray(),
                Warnings = evaluationResult.Warnings.ToArray()
            };

            if (index >= 0)
            {
                entries[index] = entry;
            }
            else
            {
                entries.Add(entry);
            }

            await WriteDatabaseUnsafeAsync(new VideoAnalysisMemoryDatabase(SchemaVersion, entries.ToArray()), cancellationToken);
            return entry;
        }
        finally
        {
            _gate.Release();
        }
    }

    /// <summary>
    /// 用来源链接生成稳定键；查询片段会保留，页面锚点会删除。
    /// Build a stable key from the source URL; query is preserved and fragment is removed.
    /// 最近修改时间：2026-06-25；修改人：GG。
    /// </summary>
    public static string BuildSourceKey(string sourceUrl)
    {
        var normalizedSourceUrl = NormalizeSourceUrl(sourceUrl);
        var bytes = SHA256.HashData(Encoding.UTF8.GetBytes(normalizedSourceUrl));
        return Convert.ToHexString(bytes).ToLowerInvariant();
    }

    /// <summary>
    /// 构建转写记忆条目，保留既有 AI 评价字段并更新转写字段。
    /// Build a transcript memory entry while preserving existing AI evaluation fields.
    /// 最近修改时间：2026-06-25；修改人：GG。
    /// </summary>
    private static VideoAnalysisMemoryEntry BuildTranscriptEntry(
        VideoAnalysisMemoryEntry? existing,
        string sourceKey,
        string sourceUrl,
        VideoSourceMetadata metadata,
        string title,
        string transcriptText,
        string? transcriptPath,
        DateTimeOffset now,
        bool incrementTaskCount = true)
    {
        return new VideoAnalysisMemoryEntry(
            sourceKey,
            sourceUrl,
            NormalizeTitle(title, metadata.Title),
            NormalizeText(metadata.Website) ?? "未知网站",
            NormalizeText(metadata.PublisherName),
            metadata.ViewCount,
            transcriptText.Trim(),
            string.IsNullOrWhiteSpace(transcriptPath) ? existing?.TranscriptPath : transcriptPath,
            existing?.CreatedAt ?? now,
            now,
            now,
            existing?.LastEvaluatedAt,
            Math.Max(0, existing?.TaskCount ?? 0) + (incrementTaskCount ? 1 : 0),
            existing?.LastReportPath,
            existing?.Category,
            existing?.OverallScore,
            existing?.TruthfulnessScore,
            existing?.TimelinessScore,
            existing?.InformationProfessionalismScore,
            existing?.EntertainmentScore,
            existing?.EmotionalGuidanceSuspicionScore,
            existing?.Verdict,
            existing?.KeyClaims ?? Array.Empty<string>(),
            existing?.ClaimEvaluations ?? Array.Empty<AiClaimEvaluation>(),
            existing?.Warnings ?? Array.Empty<string>());
    }

    /// <summary>
    /// 读取数据库文件；文件不存在时返回空数据库。
    /// Read the database file; return an empty database when it does not exist.
    /// 最近修改时间：2026-06-25；修改人：GG。
    /// </summary>
    private async Task<VideoAnalysisMemoryDatabase> ReadDatabaseUnsafeAsync(CancellationToken cancellationToken)
    {
        if (!File.Exists(_databasePath))
        {
            return new VideoAnalysisMemoryDatabase(SchemaVersion, Array.Empty<VideoAnalysisMemoryEntry>());
        }

        try
        {
            await using var stream = File.OpenRead(_databasePath);
            var database = await JsonSerializer.DeserializeAsync<VideoAnalysisMemoryDatabase>(
                stream,
                JsonOptions,
                cancellationToken);
            return database ?? new VideoAnalysisMemoryDatabase(SchemaVersion, Array.Empty<VideoAnalysisMemoryEntry>());
        }
        catch (JsonException ex)
        {
            throw new InvalidOperationException($"记忆数据库文件格式无效：{_databasePath}", ex);
        }
    }

    /// <summary>
    /// 原子写入数据库文件，避免程序中途退出时留下半截 JSON。
    /// Atomically write the database file so interrupted runs do not leave partial JSON.
    /// 最近修改时间：2026-06-25；修改人：GG。
    /// </summary>
    private async Task WriteDatabaseUnsafeAsync(
        VideoAnalysisMemoryDatabase database,
        CancellationToken cancellationToken)
    {
        var directory = Path.GetDirectoryName(_databasePath);
        if (!string.IsNullOrWhiteSpace(directory))
        {
            Directory.CreateDirectory(directory);
        }

        var tempPath = _databasePath + ".tmp";
        await File.WriteAllTextAsync(
            tempPath,
            JsonSerializer.Serialize(database, JsonOptions),
            Encoding.UTF8,
            cancellationToken);
        File.Move(tempPath, _databasePath, overwrite: true);
    }

    /// <summary>
    /// 规范化来源链接用于去重；保留 query 是为了区分同页不同分 P 或音频参数。
    /// Normalize the source URL for deduplication; query is preserved for page-part or audio parameters.
    /// 最近修改时间：2026-06-25；修改人：GG。
    /// </summary>
    private static string NormalizeSourceUrl(string sourceUrl)
    {
        var trimmedUrl = sourceUrl.Trim();
        if (!Uri.TryCreate(trimmedUrl, UriKind.Absolute, out var uri))
        {
            return trimmedUrl;
        }

        var builder = new UriBuilder(uri)
        {
            Scheme = uri.Scheme.ToLowerInvariant(),
            Host = uri.Host.ToLowerInvariant(),
            Fragment = string.Empty
        };
        return builder.Uri.AbsoluteUri.TrimEnd('/');
    }

    /// <summary>
    /// 清理短文本字段，避免把空白写入数据库。
    /// Normalize short text fields before writing them to the database.
    /// 最近修改时间：2026-06-25；修改人：GG。
    /// </summary>
    private static string? NormalizeText(string? text)
    {
        return string.IsNullOrWhiteSpace(text)
            ? null
            : text.Trim();
    }

    /// <summary>
    /// 优先使用明确标题，其次使用元数据标题，最后使用固定兜底标题。
    /// Prefer explicit title, then metadata title, and finally a fixed fallback title.
    /// 最近修改时间：2026-06-25；修改人：GG。
    /// </summary>
    private static string NormalizeTitle(string? title, string? metadataTitle)
    {
        var normalizedTitle = NormalizeText(title) ?? NormalizeText(metadataTitle);
        return string.IsNullOrWhiteSpace(normalizedTitle)
            ? "视频转写文本"
            : normalizedTitle;
    }

    /// <summary>
    /// JSON 数据库根对象。
    /// JSON database root object.
    /// 最近修改时间：2026-06-25；修改人：GG。
    /// </summary>
    private sealed record VideoAnalysisMemoryDatabase(
        int SchemaVersion,
        VideoAnalysisMemoryEntry[] Entries);
}
